name: "Setup"
description: "Setup Environment"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: "18.x"
        cache: "yarn"
    - name: Install dependencies
      shell: bash
      run: |
        yarn --frozen-lockfile
