name: PRE-CHECKS

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run tests
        run: yarn test --coverage
      - name: Upload test coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Test coverage
          path: |
            ./coverage

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Run audit
        run: yarn audit

  artifacts:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: ./.github/actions/setup
      - name: Build packages
        run: |
          yarn build
      - name: Upload production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Static Build folder
          path: |
            ./build
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: Static Build folder
