name: Upload-S3

on:
  push:
    branches:
      - main

jobs:
  uploadS3:
    runs-on: ubuntu-latest
    steps:
      - name: Upload production artifacts
        uses: actions/download-artifact@v3
        with:
          name: Static Build folder
          path: |
            ./build
